apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-openldap
  labels:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: openldap
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 389
              name: ldap
          env:
            - name: LDAP_ORGANISATION
              value: {{ .Values.organization | quote }}
            - name: LDAP_DOMAIN
              value: {{ .Values.domain | quote }}
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-openldap
                  key: adminPassword
            - name: LDAP_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-openldap
                  key: configPassword
          volumeMounts:
            - name: seed-ldif
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
              readOnly: true
          args: ["--copy-service"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: seed-ldif
          configMap:
            name: {{ .Release.Name }}-openldap-seed
