apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openldap
  labels:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/instance: {{ .Release.Name }}
