apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pgaas-selfsigned-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgaas-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: pgaas-root-ca
  subject:
    organizations:
      - PGaaS
  duration: 87600h
  renewBefore: 8760h
  secretName: pgaas-root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: pgaas-selfsigned-bootstrap
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pgaas-ca-issuer
spec:
  ca:
    secretName: pgaas-root-ca-secret
