image:
  repository: osixia/openldap
  tag: "1.5.0"
  pullPolicy: IfNotPresent

organization: PGaaS
domain: pgaas.local
baseDn: dc=pgaas,dc=local

adminPassword: admin
configPassword: config

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 200m

service:
  type: ClusterIP
  port: 389

seedUsers:
  - cn: dbadmin
    sn: Admin
    uid: dbadmin
    password: dbadmin123
  - cn: developer
    sn: Developer
    uid: developer
    password: developer123
