{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.tls.issuerName }}
    kind: {{ .Values.tls.issuerKind }}
  commonName: {{ .Release.Name }}-pgadmin4
  dnsNames:
    {{- toYaml .Values.tls.dnsNames | nindent 4 }}
  usages:
    - server auth
    - digital signature
    - key encipherment
{{- end }}
