{{- if and .Values.ldap.enabled .Values.ldap.bindPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgadmin4-ldap-bind
  labels:
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.ldap.bindPasswordKey }}: {{ .Values.ldap.bindPassword | quote }}
{{- end }}
