{{- if .Values.defaultPasswordCreate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultPasswordSecret }}
  labels:
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    pgaas.io/note: "Replace with actual pgAdmin password"
type: Opaque
stringData:
  {{ .Values.defaultPasswordKey }}: "changeme"
{{- end }}
